### ISSUE TITLE
Finch framework - distinguish between empty cache and no network results

### ISSUE THREAD

**Issue by goat000** [bmeike/ProgrammingAndroid2Examples#1]
Hi.  Your README instructed me to send comments to an email address that bounced, so I'm opening a ticket instead in hopes that you'll see it while working on the second edition.

I've been working on a project that uses the Finch RESTful Content Provider framework from this book. One problem we keep running into is how to distinguish between "We're showing 0 results because the cache is empty and we're waiting on a network call" and "We're showing 0 results because the server just told us there are 0 results." We'd like to show a "Loading..." message in the first case and a "No results" message in the second.

It doesn't seem that the Finch framework, as explored in Chapter 13, allows the querying activity to distinguish between the two. We've worked through some ideas, but without satisfaction so far, and the remaining ideas are far from elegant. I think it would be a useful addition to the second edition discuss a way to handle this.

**Comment by ldornin** [comment]
Brian,

Did you get the email that I just sent?

Thanks,

Laird

On Thu, Jun 28, 2012 at 10:06 PM, Brian Williammee
reply@reply.github.com
wrote:

**Comment by poshaughnessy** [comment]
Hi,

I'm just starting to explore Programming Android Chapter 13 and the Finch Framework, so apologies if this is out of place at all, but Brian's question sounds like a good one - I would also need to distinguish zero results in the same way. Is it possible to copy the response here, or email it to me too?

Thank you,

Peter
