### ISSUE TITLE
Where is tools/ide/eclipse path referenced in README ?

### ISSUE THREAD

**Issue by paulvi** [bmeike/ProgrammingAndroid2Examples#11]
Where is tools/ide/eclipse path referenced in README ?

**Comment by bmeike** [comment]
Hi Paul,
  Each project has a tools directory, and each of those tools directories contains an ide directory, containing an eclipse file.  Here's an example:

https://github.com/bmeike/ProgrammingAndroid2Examples/tree/master/AndroidUIDemo/tools/ide/eclipse
