### ISSUE TITLE
The Dots Demo

### ISSUE THREAD

**Issue by sgurukrupa** [bmeike/ProgrammingAndroid2Examples#9]
The text at page number 185 says that the complete code for The Dots demo (Example 6-7 listing in the book) is available on the web page of the book. Where is it?

**Comment by bmeike** [comment]
The book gives the location of the book repository in several places:
https://github.com/bmeike/ProgrammingAndroidExamples.  The ”dots" project
is called AndroidUIDemo.

-blake
